export const DOCTORS_LIST_REQUEST = "DOCTORS_LIST_REQUEST"
export const DOCTORS_LIST_SUCCESS = "DOCTORS_LIST_SUCCESS"
export const DOCTORS_LIST_FAIL = "DOCTORS_LIST_FAIL"

export const DOCTOR_REQUEST = "DOCTOR_REQUEST"
export const DOCTOR_SUCCESS = "DOCTOR_SUCCESS"
export const DOCTOR_FAIL = "DOCTOR_FAIL"
