export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST"
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS"
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL"
export const NEWS_LIST_RESET = "NEWS_LIST_RESET"

export const CREATE_NEW_SUCCESS = "CREATE_NEW_SUCCESS"
export const CREATE_NEW_FAIL = "CREATE_NEW_FAIL"
export const CREATE_REQUEST_END = "CREATE_REQUEST_END"
